export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const SET_RESOURCES = 'SET_RESOURCES';
export const ADD_RESOURCE = 'ADD_RESOURCE';
export const RESOURCE_FETCHED = 'RESOURCE_FETCHED';
export const UPDATE_RESOURCE = 'UPDATE_RESOURCE';
export const DELETE_RESOURCE = 'DELETE_RESOURCE';

export const SET_ALL_RESOURCES = 'SET_ALL_RESOURCES';

export const SET_ALLWEB_RESOURCES = 'SET_ALLWEB_RESOURCES';