export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const SET_RESOURCES = 'SET_RESOURCES';
export const ADD_RESOURCE = 'ADD_RESOURCE';
export const RESOURCE_FETCHED = 'RESOURCE_FETCHED';
export const UPDATE_RESOURCE = 'UPDATE_RESOURCE';
export const DELETE_RESOURCE = 'DELETE_RESOURCE';

export const SET_ALL_RESOURCES = 'SET_ALL_RESOURCES';
export const LOCATION_RESOURCE_FETCHED = 'LOCATION_RESOURCE_FETCHED';

export const SET_ALLWEB_RESOURCES = 'SET_ALLWEB_RESOURCES';
export const ADD_ALLWEB_RESOURCE = 'ADD_ALLWEB_RESOURCE';
export const ALL_RESOURCE_FETCHED = 'ALL_RESOURCE_FETCHED';

export const BALANCE_FETCHED = 'BALANCE_FETCHED';
export const OWNER_BALANCE_FETCHED = 'OWNER_BALANCE_FETCHED';
export const SET_USER = 'SET_USER';

export const ADD_RESOURCE_To_MYSQL = 'ADD_RESOURCE_To_MYSQL';
export const BUY_RESOURCE_FETCHED = 'BUY_RESOURCE_FETCHED';
export const SET_BUY_RESOURCES = 'SET_BUY_RESOURCES';

export const ADD_BUY_RESOURCE = 'ADD_BUY_RESOURCE';
export const SET_BUYER_RESOURCES = 'SET_BUYER_RESOURCES';
export const SET_BLOCK_USER = 'SET_BLOCK_USER';

export const SET_OWNER_ID = 'SET_OWNER_ID';
export const SET_FILEINFO = 'SET_FILEINFO';
export const SET_ALLWEB_FILEINFO = 'SET_ALLWEB_FILEINFO';